"""Add source download support

Revision ID: 80d458ac424c
Revises: adc65fcc95bc
Create Date: 2025-10-26 08:30:31.767399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d458ac424c'
down_revision: Union[str, None] = 'adc65fcc95bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_configs', sa.Column('source_url', sa.String(length=1023), nullable=True))
    op.add_column('project_configs', sa.Column('extract_command', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_configs', 'extract_command')
    op.drop_column('project_configs', 'source_url')
    # ### end Alembic commands ###
