"""Add subproject_path to projects

Revision ID: adc65fcc95bc
Revises: 
Create Date: 2025-10-26 08:21:00.212479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc65fcc95bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('subproject_path', sa.String(length=511), nullable=True))
    op.drop_constraint(op.f('projects_full_name_key'), 'projects', type_='unique')
    op.create_index('idx_projects_unique', 'projects', ['full_name', 'subproject_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_projects_unique', table_name='projects')
    op.create_unique_constraint(op.f('projects_full_name_key'), 'projects', ['full_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'subproject_path')
    # ### end Alembic commands ###
